### ISSUE TITLE
jq throwing a "Too many arguments" error in download.sh

### ISSUE THREAD

**Issue by rmx90210** [exactlylabs/fcc-broadbandmap-dataloader#1]
I'm getting a `Too many arguments` on [this line](https://github.com/exactlylabs/fcc-broadbandmap-dataloader/blob/master/download.sh#L7) when piping the data downloads JSON to `jq`.

```bash
./download.sh: line 9: /opt/homebrew/bin/jq: Argument list too long
./download.sh: line 10: /opt/homebrew/bin/jq: Argument list too long
./download.sh: line 12: /bin/mkdir: Argument list too long
```

Doing some digging...

**Comment by rmx90210** [comment]
Hmm, it seems to work for me if I remove the `export`s from the variable declarations. Not a bash person but my [understanding](https://www.baeldung.com/linux/bash-variables-export) is `export`'s only needed if you're spinning up child shells.

**Comment by untoldone** [comment]
This should be corrected in the latest versions given your applied changes but let me know if you still see it anywhere
