### ISSUE TITLE
curl balking if file already exists

### ISSUE THREAD

**Issue by rmx90210** [exactlylabs/fcc-broadbandmap-dataloader#2]
If I run the script more than once I'm getting an error:

```
Warning: Failed to open the file 
Warning: ./working/national/bdc_us_broadband_summary_by_geography_063022: File 
Warning: exists
```

I'm not seeing an obvious way to tell curl to skip the file if it already exists _and_ fetch the remote file name with `-OJ`. It seems like either we'd need to wipe out the downloads each time, or tell curl what to name the local files.

**Comment by untoldone** [comment]
I think this no longer applies with the new sync script but let me know if its still an issue
