### ISSUE TITLE
Unify.sh error

### ISSUE THREAD

**Issue by ILSR-GIS-DATA** [exactlylabs/fcc-broadbandmap-dataloader#5]
Receiving this error when I run unify.sh:

![image](https://github.com/exactlylabs/fcc-broadbandmap-dataloader/assets/99908618/ab7ca67e-7a92-4ce7-a37c-eda46c2366fe)

I do see an index file in the "storage" folder, but it appears empty.

**Comment by untoldone** [comment]
@rbrtmrtn just submitted a fix so it'll tell you which file wasn't downloaded, however, this shows up if you haven't downloaded all the files yet for the latest process / updated id. What shows up when you run sync right now? @ILSR-GIS-DATA

**Comment by ILSR-GIS-DATA** [comment]
Okay, I updated both the sync & unify scripts, and then realized it was actually sync causing the problem because I didn't have 'unzip' installed for bash to do its thing.
